### ISSUE TITLE
请问为什么要添加tcpserver类

### ISSUE THREAD

**Issue by hasegetc** [kuafuwang/LspCpp#1]
kuafuwang，您好，我正在研究lsp，有几个问题想请教下
1、为什么添加tcpserver类，请问client和server是通过tcp进行json-rpc数据交换的吗？
2、为什么不考虑websocket呢？很奇怪vs code没有原生支持websocket，但theia支持了websocket。lsp sdk中，java sdk支持websocket，您这个sdk是支持tcp的吧？
3、运行gitpod，我感觉lsp的client和server都是运行在远程容器里，client和server都通过IPC交互，不知道正不正确？
希望方便的时候帮忙解答下，感谢！

**Comment by kuafuwang** [comment]
1.client 和server一般是不同的进程中,这时候他们之间通信就是进程间通信,进程间通信有多种方式,有管道,有tcp.我们使用这个库的时候即用到了管道也用到tcp.两者都支持,看你需要.因为我们用到的JcKit这个产品中,调试器中作为使用到了tcpdserver.
[你可以看看我们工具的构架:] JCIDE的构架(https://www.javacardos.com/javacardforum/viewtopic.php?f=5&t=2108)

2.websocket 不也是tcp实现的吗?我们的Jckit中scp是python 写的.里面的websocket就是tcp的

3.IPC 的意思（Inter-Process Communication，进程间通信）

**Comment by kuafuwang** [comment]
`RemoteEndPoint(std::istream& in, std::ostream& out, MessageJsonHandler& json_handler, Endpoint& localEndPoint, lsp::Log& _log,uint8_t max_workers = 2);;`
你看这个就是我们的库的通信的一个核心类. 你只要保证你的IPC的通信方式in 和out  实现了c++的流的操作模式,就支持通信.无论你是管道还是tcp还是其他的.

**Comment by kuafuwang** [comment]
> kuafuwang，您好，我正在研究lsp，有几个问题想请教下
> 1、为什么添加tcpserver类，请问client和server是通过tcp进行json-rpc数据交换的吗？
> 2、为什么不考虑websocket呢？很奇怪vs code没有原生支持websocket，但theia支持了websocket。lsp sdk中，java sdk支持websocket，您这个sdk是支持tcp的吧？
> 3、运行gitpod，我感觉lsp的client和server都是运行在远程容器里，client和server都通过IPC交互，不知道正不正确？
> 希望方便的时候帮忙解答下，感谢！

[https://www.cnblogs.com/merray/p/7918977.html](从上面的图中可以看出，HTTP、WebSocket 等应用层协议，都是基于 TCP 协议来传输数据的。我们可以把这些高级协议理解成对 TCP 的封装。)

**Comment by hasegetc** [comment]
谢谢解答，还有个小问题：请问LSP的client，能直接运行在浏览器吗？

**Comment by kuafuwang** [comment]
> 谢谢解答，还有个小问题：请问LSP的client，能直接运行在浏览器吗？

浏览器是什么意思?  在node的运行环境中可以的.

**Comment by hasegetc** [comment]
是的，我是发现在gitpod中，LSP client和server都是运行在远程的node环境中的。比如client和server的tcp通信，是由node所在远程机器和server远程机器之前，不是浏览器所在机器和server机器之间。想着如果能将tcp的client端放在浏览器，性能也许会好点

**Comment by kuafuwang** [comment]
我不了解gitpod.你可以自己试试.
