### ISSUE TITLE
demo编译不通过

### ISSUE THREAD

**Issue by hasegetc** [kuafuwang/LspCpp#16]
* 楼主，这个项目最新代码，下载下来，编译dll是成功的，切换成exe，编译自带的demo，报错

**Comment by kuafuwang** [comment]
报什么错啊.你把错误输出贴一下啊.

**Comment by kuafuwang** [comment]
> * 楼主，这个项目最新代码，下载下来，编译dll是成功的，切换成exe，编译自带的demo，报错

把错误输出黏贴给我看看.我这编译正常.

**Comment by hasegetc** [comment]
![image](https://user-images.githubusercontent.com/5785979/128160609-fd77339e-2c74-42f5-b511-7035f668f660.png)
感觉与boost版本升级有关

**Comment by kuafuwang** [comment]
这个是不是你的问题啊.

**Comment by kuafuwang** [comment]
我上传的时候.sln文件是在LspCpp文件夹的父目录中,boost 所在的package也是在LspCpp文件夹的父目录中.

**Comment by kuafuwang** [comment]
另外一个解决方法是你通过nutget移除依赖boost依赖,然后在添加回来.

**Comment by hasegetc** [comment]
我的问题，直接切配置管理器就可以。不好意思，之前是直接在dll配置管理器中改的
![image](https://user-images.githubusercontent.com/5785979/128335983-22e2ac1e-bc66-4104-9d5c-6f757a9fe74c.png)
