### ISSUE TITLE
是否应该支持websocket无header传输方式

### ISSUE THREAD

**Issue by hasegetc** [kuafuwang/LspCpp#17]
* 根据
 https://github.com/microsoft/language-server-protocol/issues/86#issuecomment-252194346
https://github.com/microsoft/language-server-protocol/issues/86#issuecomment-257272415
https://github.com/TypeFox/vscode-ws-jsonrpc/issues/6
这三个地方的讨论，websocket中， lsp字段的content-length是冗余字段。
而且vscode原生有两种数据传输协议：“The first one is over streams using the described base protocol. The second is node ipc which doesn't have any header information”
请问LspCpp是否考虑：支持使用配置的方式，灵活处理协议中的header字段？

**Comment by kuafuwang** [comment]
[在我没有看到两种方式](https://github.com/microsoft/vscode-languageserver-node/blob/main/jsonrpc/src/common/messageReader.ts) 而且那是2016年说的.另外在规范上也没有看到关于这一点 [规范](https://microsoft.github.io/language-server-protocol/specifications/specification-current/).  lsp我理解就是独立于传输层的协议.虽然websocket不需要,但是别的tcp协议需要啊.

**Comment by kuafuwang** [comment]
[I documented some standard command line arguments for 3.15 and will close the issue. The specification itself still allows to rtun LSP over http.](https://github.com/microsoft/language-server-protocol/issues/86#issuecomment-724932184) 这是盖棺定论了.
