### ISSUE TITLE
使用第三方websocket，链接报错

### ISSUE THREAD

**Issue by hasegetc** [kuafuwang/LspCpp#18]
如下截图所示，只跑websocket服务端
![image](https://user-images.githubusercontent.com/5785979/128447240-2527cd34-753f-40c5-a22e-291908db44b2.png)
通过第三方工具，比如http://coolaf.com/tool/chattest，链接websocket，什么消息都不发送，开始能提示链接成功（不发送消息），但过一到两秒左右，就会自动断开，vs报如下错误
![image](https://user-images.githubusercontent.com/5785979/128447653-4a20e183-ef59-4cad-b20d-22e7333b22ed.png)
堆栈如下
![image](https://user-images.githubusercontent.com/5785979/128447184-bc7a39c4-9eaf-4956-b4a2-7e4ef86a4c83.png)

请问是不是哪里设置了超时时间？

**Comment by kuafuwang** [comment]
![1](https://user-images.githubusercontent.com/3636678/128451557-91f0243f-cb0c-4bf7-ad68-11d3e0dfb80e.png)
我实验了一下,我的是正常的. 不过 我发现我连接之后,不关闭上一次连接,然后我在服务器那主动断开上一个连接的时候,会有异常抛出.我处理了一下. 不过我这库是给LSP库用的,而且只是支持单连接.这个不一定符合你的需要吧.

**Comment by hasegetc** [comment]
请问只是支持单连接是指一个进程只能一个websocket链接吗？

**Comment by kuafuwang** [comment]
> 请问只是支持单连接是指一个进程只能一个websocket链接吗？
LSP 中,一般是一对一的, 所以我写的server 在另一个连接过来的时候关闭之前的连接(如果 有的话).

**Comment by kuafuwang** [comment]
> 请问只是支持单连接是指一个进程只能一个websocket链接吗？

有些server只是accept第一个连接.如果你需要多连接,你得自己实现一个websocket server , 另外你并不需要lps吧.你只是需要json序列化相关的功能而已.

**Comment by kuafuwang** [comment]
你更新一下就可以解决你描述的问题了

**Comment by hasegetc** [comment]
受教了，谢谢楼主
