### ISSUE TITLE
tcp实现会频繁ack，且ack耗时较长

### ISSUE THREAD

**Issue by hasegetc** [kuafuwang/LspCpp#19]
楼主好：
      

-  随便定义一个简单的lsp请求，使用tcp或者websocket在内网两台电脑间通信，会发现ping 耗时10ms的网络，一次jsonrpc请求会到150ms左右。定位发现，"\r\n\r\n"会造成tcp每次都会对Content-length数据发送ACK，如截图所示
- 如果将实现，改成如下方式，请求会到20ms左右
-  不知道是不是应用层直接在流中输出"\r\n\r\n"会触发tcp层 ack造成的

![微信截图_20210824140610](https://user-images.githubusercontent.com/5785979/130564844-29df4ea1-2552-4765-9737-6b77d71aa079.png)

```
void LspMessage::Write(std::ostream& out) {
	rapidjson::StringBuffer output;
	rapidjson::Writer<rapidjson::StringBuffer> writer(output);
	JsonWriter json_writer{ &writer };
	ReflectWriter(json_writer);

	const auto& s = output.GetString();
	const auto value = std::string("Content-Length: ") + std::to_string(output.GetSize()) + "\r\n\r\n" + s;
	out << value;

	out.flush();
}
```

````
void WriterMsg(std::shared_ptr<lsp::ostream>&  output, LspMessage& msg)
{
	const auto& s = msg.ToJson();
	const auto value =
		std::string("Content-Length: ") + std::to_string(s.size()) + "\r\n\r\n" + s;
	output->write(value);
	//output->write(s);
	output->flush();
}
```

**Comment by kuafuwang** [comment]
网络通信是基于用的boost的asio来实现. 我之前在分两次write,你改成一次之后,如果消息比较短的话, 那asio那边应该不分包吧,所有ack次数变少. 你把这个改动提交一下.

**Comment by kuafuwang** [comment]
我对tcp实际上不怎么了解.我之前也没有考虑过这个效率.

**Comment by hasegetc** [comment]
也许是这个问题引起来的，延时ack：
https://blog.csdn.net/wdscq1234/article/details/52430382
