### ISSUE TITLE
Could you write the human-readable text in English, not in Chinese?

### ISSUE THREAD

**Issue by KOLANICH** [kuafuwang/LspCpp#2]

**Comment by kuafuwang** [comment]
I can write it in Chinese ,then translate it with google translate in  this weekend . That's the only thing i can do. I'm not  good at English.

**Comment by KOLANICH** [comment]
The **only** way to be good in a language is to use (not learn, but actually **use**) it every day. So it is OK to make mistakes. Only ones who do nothing do no mistakes.

So, just write in English and don't worry about your spelling and grammar much. People may send PRs, if your mistake will be too drastic.

**Comment by kuafuwang** [comment]
OK. I  had rewrite  the readme.md  with English. I will try to write text in English.

**Comment by KOLANICH** [comment]
Thank you.
