### ISSUE TITLE
你这个库被Asymptote在使用，牛！

### ISSUE THREAD

**Issue by asmwarrior** [kuafuwang/LspCpp#21]
Asymptote是一个矢量图绘制软件：https://github.com/vectorgraphics/asymptote

我问个问题，你这个库是主要用于server端的lsp么？

如果是client端的lsp，也需要用你这个库么？我指的是C++的lsp的客户端。
参见这个讨论：

[an easy cpp language-server-protocol client(C++)](https://forums.codeblocks.org/index.php/topic,24276.0/all.html)

[Code completion using LSP and clangd](https://forums.codeblocks.org/index.php/topic,24357.0.html)

还是说对于一个编辑器来说，只需要类似：[alextsao1999/lsp-cpp: an easy cpp language-server-protocol client](https://github.com/alextsao1999/lsp-cpp)
这样的就可以了？

**Comment by kuafuwang** [comment]
那时候参考[lsp4j](https://github.com/eclipse/lsp4j)既可以当server,也能当client.
我主要是给一个javacard  开发套件 [Jckit](https://www.javacardos.com/tools)用的. 给JCIDE编辑器用的时候client.
给调试转接器用时候是server.
我后来给我写的一个parser 生成器提供[lsp sever](https://github.com/A-LPG/LPG-language-server) 的时候用的它可以用来写server.

至于clangd,我也研究过,从中摘取过代码加到这个库中.
我觉得clangd也不错.我觉得不能满足我. clangd得用LLVM那一套,我不想引进来我的工程中. 而an easy cpp language-server-protocol client(C++)我觉得依赖比较少是优点,但是 不方便我扩展协议.和在一个工具同时支持多lsp client.
所有我才写了这个库.另外这个库大量参考了cquery,所以我开源出来.
库选择适合自己的就行. 我写的那个JCDIE,中的scp是用Python写的.我也用了python的lsp server. 你看我不拘泥于语言,我一般能 用现成的就用现成,实在不行才自己.

**Comment by kuafuwang** [comment]
我在JCIDE启动了3个lsp client. 一个lsp client是和[JDT.LS](https://github.com/eclipse/eclipse.jdt.ls)这个基于JDT的用于Java的 lsp server 通信.
一个lsp client 是和[sonarlint-language-server](https://github.com/SonarSource/sonarlint-language-server) 用来进行代码lint.
一个lsp client 是也我自己写的javacard  proxy   进行javacard 相关业务通信的lsp server.
每一个client 都有他们自定义的协议.这lsp除了用来处理语言,也可以扩展协议,把它当成自定义协议库嘛.

**Comment by kuafuwang** [comment]
clangd,你们在用吗? 按理说处理C++的IDE,应该用得到clangd,cquery,ccls其中的一个吧. 我觉得如果你熟悉LLVM和clangd,给他加上client相关部分也是不错的.毕竟他的代码质量好啊.

**Comment by kuafuwang** [comment]
我打不开你们论坛,我翻墙了也打不开,不知道为什么.但是我觉得 Code completion using LSP and clangd 是非常对的.
我以前JCID 3.0之前用的自己写的 java 代码解析,完成,提示, 就是这个库[JCDT](https://github.com/kuafuwang/JCDT). 可以说他是我的亲儿子啊,但是我后来把它砍了.换成了LSP和jdt.ls. 因为换了之后 工程稳定性和扩展性 大幅度提高.

**Comment by asmwarrior** [comment]
> 我打不开你们论坛,我翻墙了也打不开,不知道为什么.但是我觉得 Code completion using LSP and clangd 是非常对的. 我以前JCID 3.0之前用的自己写的 java 代码解析,完成,提示, 就是这个库[JCDT](https://github.com/kuafuwang/JCDT). 可以说他是我的亲儿子啊,但是我后来把它砍了.换成了LSP和jdt.ls. 因为换了之后 工程稳定性和扩展性 大幅度提高.

codeblocks的论坛我这里打开没有问题，貌似这个论坛只能用IPV4的方式浏览，如果你是IPV6的话，可能是有问题的。

你在LSP上玩得比较溜了，我基本是初学者，我以前是直接在维护CB里面自带的那个C++的parser，到了C++语法多的时候，基本没法搞了，只能借助外部的LSP来搞。

**Comment by kuafuwang** [comment]
> > 我打不开你们论坛,我翻墙了也打不开,不知道为什么.但是我觉得 Code completion using LSP and clangd 是非常对的. 我以前JCID 3.0之前用的自己写的 java 代码解析,完成,提示, 就是这个库[JCDT](https://github.com/kuafuwang/JCDT). 可以说他是我的亲儿子啊,但是我后来把它砍了.换成了LSP和jdt.ls. 因为换了之后 工程稳定性和扩展性 大幅度提高.
> 
> codeblocks的论坛我这里打开没有问题，貌似这个论坛只能用IPV4的方式浏览，如果你是IPV6的话，可能是有问题的。
> 
> 你在LSP上玩得比较溜了，我基本是初学者，我以前是直接在维护CB里面自带的那个C++的parser，到了C++语法多的时候，基本没法搞了，只能借助外部的LSP来搞。

我可以理解你.因为我现在维护的工具我接手的时候是一个LL1的 手写的java parser. 只有词法分析,和语法分析.语义分析没有.
我很不满意,然后我就找了一个以前IBM 用c++写的java 编译器.我拿过来改. 我加了许多东西进去.但是我又要维护编辑器,编译器,调试器.所以java语法一旦升级,我就很累. 我 尝试后来在c++ 中调用jvm.dll, 因为我对JDT的compiler比较熟,就在java子进程中用JDT compiler来解析,然后通过自定的rpc协议来传递结果.但是不知道为什么jdk 8之后的jvm.dll,我调用的时候总是崩溃. 不得已我我才转到LSP来的. 另外我也是看LSP协议很成熟了,各个主流IDE和编辑器都支持它.

我维护的一个eclipse扩展,里面也用到用到lsp4j.  因为我把原来的工具都模块化,做成一个个小工具,然后各个工具通过LSP来实现多进程通信. 而且这种模式不局限语言.各种语言些的工具都可以组合起来.

**Comment by kuafuwang** [comment]
其实调试模块你也可以考虑DAP协议[cppdap](https://github.com/google/cppdap),我的工具中用到了这个,我原本是打算自己写的.后来发现谷歌开源了这个库,我高兴坏了.我给它找了不少bug.我是拿它当成dap client来用的. 他也可以写dap server.不过server一般编辑器用不上. 要实现语言调试器的人才需要.
