### ISSUE TITLE
添加两个能直接运行的demo？

### ISSUE THREAD

**Issue by hasegetc** [kuafuwang/LspCpp#3]
请问是否方便添加两个能直接运行的demo，或者将D:/test  ddd/testdfdf/testdfdf/src/com/nxp/cas/SC/ecka/ECKA.java，C:\workspace\J3R_SC_ECKA\bin\com\nxp\cas\SC\ecka\javacard\ecka.cap这两个文件上传上来，方便学习？

**Comment by kuafuwang** [comment]
我添加了一个可以直接运行的demo,下载下来编译一下,在VS中选择console这个编译选项,就可以编译了.
