### ISSUE TITLE
多个客户端连接的问题

### ISSUE THREAD

**Issue by landing-success** [kuafuwang/LspCpp#37]
你好，请问能否提供多个客户端连接的支持，目前在进行server连接的时候，新的连接进来会出问题。

**Comment by kuafuwang** [comment]
你是想用在其他地方，而非 lsp 吗？以前有人提过这个需求。

**Comment by landing-success** [comment]
是的，主要是想同时处理本地多个脚本的连接，有这个需求

**Comment by kuafuwang** [comment]
https://github.com/kuafuwang/LspCpp/issues/18

**Comment by landing-success** [comment]
好的，谢谢

**Comment by kuafuwang** [comment]
你在 boost 的 example 中找一个 sever-client 的 而且支持多连接 的例子， 然后用这个库提供的序列号和反序列化功能，就能满足你需求了。

**Comment by landing-success** [comment]
ok，我找一下

**Comment by kuafuwang** [comment]
> 是的，主要是想同时处理本地多个脚本的连接，有这个需求

lsp 是可以设置 sever 多线程 worker 的。 单连接，然后发不同的脚本过来，server 会在调度到线程池里同时进行处理，这样说不定也可以。

**Comment by landing-success** [comment]
这个该如何设置，请教一下

**Comment by kuafuwang** [comment]
```
    explicit TcpServer(const std::string& address, const std::string& port,
                std::shared_ptr < MessageJsonHandler> json_handler,
                std::shared_ptr < Endpoint> localEndPoint, lsp::Log& ,uint32_t _max_workers = 2);

```
你设置一下。不过你在 client 那发 request 的话要做同步，不能同时发 request. 要以此发脚本的内容。就是通信是不是并行是串行的

**Comment by kuafuwang** [comment]
```
    explicit TcpServer(const std::string& address, const std::string& port,
                std::shared_ptr < MessageJsonHandler> json_handler,
                std::shared_ptr < Endpoint> localEndPoint, lsp::Log& ,uint32_t _max_workers = 2);

```
你设置一下。不过你在 client 那发 request 的话要做同步，不能同时发 request. 要以此发脚本的内容。就是通信是不是并行是串行的

**Comment by landing-success** [comment]
这边我也有设置过，不过我的需求主要难点就是脚本客户端是并发的，做不了同步操作，只能在server端处理
