### ISSUE TITLE
Missing license?

### ISSUE THREAD

**Issue by KevinEady** [kuafuwang/LspCpp#4]
I noticed that this repository does not have a license file. From [GitHub's licensing page](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/licensing-a-repository#choosing-the-right-license):

> However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work.

Do you plan to add a license, so others can include this in their projects? The GitHub interface should allow you to [add a license](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/adding-a-license-to-a-repository) directly within the browser.

Thanks, Kevin

**Comment by kuafuwang** [comment]
MIT
