### ISSUE TITLE
如何使用？

### ISSUE THREAD

**Issue by KermanX** [kuafuwang/LspCpp#7]
@kuafuwang
要写一个嵌入式语言
（高亮在C++中的#$开头的代码）
从哪里开始？
谢谢你的LspCpp！

**Comment by kuafuwang** [comment]
> @kuafuwang
> 要写一个嵌入式语言
> （高亮在C++中的#$开头的代码）
> 从哪里开始？
> 谢谢你的LspCpp！

语言server  <---------lsp-------> editor(类似vscode)  
你现在有server了吗? 没有server,就要自己写server啊. 就是要写解析你的嵌入式语言的sever. 
如果没有现成的,那你应该通过写该语言词法解析器,语法解析器得到解析,然后按照LSP协议,把解析结构转成lsp需要的结构
你是想问怎么写解析代码吗?

**Comment by kuafuwang** [comment]
[cquery](https://github.com/jacobdufault/cquery) 这个工程是c/c++ 的一个lsp端的server.

**Comment by KermanX** [comment]
是的

**Comment by KermanX** [comment]
所以，我应该先用cquery写好server，再用lspcpp吗？

**Comment by kuafuwang** [comment]
> 所以，我应该先用cquery写好server，再用lspcpp吗？

cquery 不符合你的需要吧.它是处理c++,你的是扩展c++的语言吗? lspcpp和server没有关系.可以不用lspcpp.
如果是扩展的c++ 语言,你要写好好解析代码,得会编译原理吧.看你提问,感觉你这方面是小白啊.

**Comment by KermanX** [comment]
是的。初中生

**Comment by kuafuwang** [comment]
> 是的。初中生

你可以用正则表达式匹配#$开始的语句. 你在哪里高亮啊?在哪个编辑器啊?

**Comment by KermanX** [comment]
我的计划是：
实现一种高级的C++预处理器
给原来那个只能处理超烂宏定义的预处理器上加一层
让编译步骤变成：
源代码->我的c-pre-preprocessor->原生preprocessor->编译器

计划：写一个vsix拓展
先实现代码高亮
然后在VS（not code）里，可以像C++/WinRT一样，加一层编译步骤。（但是不知道vscode能不能做到）

**Comment by KermanX** [comment]
至于这个预处理器的语法，正在设计中
设计了不少了。所以语法肯定没问题的。

问题就是怎么写这个vsix拓展？网上的资料完全帮不到我诶
求指点

**Comment by kuafuwang** [comment]
> 我的计划是：
> 实现一种高级的C++预处理器
> 给原来那个只能处理超烂宏定义的预处理器上加一层
> 让编译步骤变成：
> 源代码->我的c-pre-preprocessor->原生preprocessor->编译器
> 
> 计划：写一个vsix拓展
> 先实现代码高亮
> 然后在VS（not code）里，可以像C++/WinRT一样，加一层编译步骤。（但是不知道vscode能不能做到）

clang的预处理不能满足你啊? cquery哪个用的就是clang

**Comment by KermanX** [comment]
完全不能诶

**Comment by kuafuwang** [comment]
> 至于这个预处理器的语法，正在设计中
> 设计了不少了。所以语法肯定没问题的。
> 
> 问题就是怎么写这个vsix拓展？网上的资料完全帮不到我诶
> 求指点

我没有写过vsix拓展.哪个和lspcpp也没有关系.

**Comment by kuafuwang** [comment]
> 至于这个预处理器的语法，正在设计中
> 设计了不少了。所以语法肯定没问题的。
> 
> 问题就是怎么写这个vsix拓展？网上的资料完全帮不到我诶
> 求指点

你先把预处理器实现再说别的吧.

**Comment by KermanX** [comment]
能否告诉我如何实现？

**Comment by KermanX** [comment]
实现成什么样子（遵循怎样的标准）？
什么语言写比较好？
有没有框架？

**Comment by kuafuwang** [comment]
> 至于这个预处理器的语法，正在设计中
> 设计了不少了。所以语法肯定没问题的。
> 
> 问题就是怎么写这个vsix拓展？网上的资料完全帮不到我诶
> 求指点

如果是我,会基于clang,改它的预处理器,加上自己想要的的功能.你先去读clang的代码吧. 然后改造成你的clang.

**Comment by KermanX** [comment]
我希望，这个升级的预处理器是每个人只要装插件就能用的

谢谢您的帮助！

**Comment by kuafuwang** [comment]
> 我希望，这个升级的预处理器是每个人只要装插件就能用的
> 
> 谢谢您的帮助！

你把clang改造好后,就可以做到了. vscode里面的c++的插件都是基于clang来实现的.
另外给我这个项目点一下star 啊.
