### ISSUE TITLE
Visual Studio编译LspCpp出错

### ISSUE THREAD

**Issue by HaoWShi** [kuafuwang/LspCpp#8]
安装环境：win10+VS2019
按照提示restore packages后，还是存在报错
![image](https://user-images.githubusercontent.com/20752268/114348626-61eaa000-9b99-11eb-8f30-33d404140ed2.png)
麻烦指导下
谢谢

**Comment by HaoWShi** [comment]
OK，I solve the problem above, but I have new issue.
Change Steps:
1、Copy ..../LspCpp/packages to ..../packages
2、Change packages.config(141->142(VS2019))
![image](https://user-images.githubusercontent.com/20752268/114356953-bdba2680-9ba3-11eb-8198-1dfeabbf3fec.png)
3、Change std::min(...) -> (std::min)(...)
4、Config lib in Visual Studio2019
![image](https://user-images.githubusercontent.com/20752268/114357137-f528d300-9ba3-11eb-81a2-88cea3324ab6.png)
 But I have another question that I can not solve below:
![image](https://user-images.githubusercontent.com/20752268/114357237-1984af80-9ba4-11eb-81f4-8bfc31a8af12.png)

**Comment by kuafuwang** [comment]
> OK，I solve the problem above, but I have new issue.
> Change Steps:
> 1、Copy ..../LspCpp/packages to ..../packages
> 2、Change packages.config(141->142(VS2019))
> ![image](https://user-images.githubusercontent.com/20752268/114356953-bdba2680-9ba3-11eb-8198-1dfeabbf3fec.png)
> 3、Change std::min(...) -> (std::min)(...)
> 4、Config lib in Visual Studio2019
> ![image](https://user-images.githubusercontent.com/20752268/114357137-f528d300-9ba3-11eb-81a2-88cea3324ab6.png)
> But I have another question that I can not solve below:
> ![image](https://user-images.githubusercontent.com/20752268/114357237-1984af80-9ba4-11eb-81f4-8bfc31a8af12.png)

package 这个没有必要这么麻烦配置吧.有时候微软的这个功能有点问题. 你把他们移除出pacakge,然后在重新加回来就行.

**Comment by kuafuwang** [comment]
要是像你这样手动添加lib和目录,那后面boost升级了,还得手动添加.

**Comment by kuafuwang** [comment]
之前我机器一直在跑机器学习的模型,特别卡.
你可以先移除
![12](https://user-images.githubusercontent.com/3636678/114358641-b4ca5480-9ba5-11eb-920d-e348c434e6ee.png)
然后在重新安装回来
![Uploading 13.png…]()

然后在安装回来. 我试过一回.微软的VS的包管理工具感觉有问题.有时候明明都restore package 了,但是没有配置到工程目录上似的.

**Comment by kuafuwang** [comment]
找不到main 函数的那个错误,你选择的是那个编译配置项?
![14](https://user-images.githubusercontent.com/3636678/114359547-ab8db780-9ba6-11eb-83c2-8d945a93b2f0.png)
是console吗? 你如果当成lib使用,要选择Debug或者release. console是我用来跑demo的.你看看配置选项中的预处理器中,把main配置成生效.

**Comment by HaoWShi** [comment]
我配置的Debug

**Comment by kuafuwang** [comment]
![16](https://user-images.githubusercontent.com/3636678/114360783-fcea7680-9ba7-11eb-9437-1d2d8f60ba32.png)
你是不是在这编译配置下,将静态库的选项  改成exe. 没有必要啊.你切换到console就行了. LspCpp是当成静态库使用的.

**Comment by HaoWShi** [comment]
非常感谢，修改为lib之后，编译通过了
![image](https://user-images.githubusercontent.com/20752268/114362207-aaaa5500-9ba9-11eb-9f97-c6092583a7c5.png)

**Comment by kuafuwang** [comment]
> 非常感谢，修改为lib之后，编译通过了
> ![image](https://user-images.githubusercontent.com/20752268/114362207-aaaa5500-9ba9-11eb-9f97-c6092583a7c5.png)

通过就好.另外这个lspcpp点个star啊.刷朋友圈要记得点赞,上github要记得点star.
