### ISSUE TITLE
使用LSPCpp定义自己的编程语言客户端

### ISSUE THREAD

**Issue by HaoWShi** [kuafuwang/LspCpp#9]
你好，我准备基于你当前的LspCpp去扩展自己的一个编程语言客户端，我已经有一个语言的server端，我该如何调用你当前的代码库去实现对代码的解析。麻烦指导下，谢谢

**Comment by kuafuwang** [comment]
这个库不是用来解析代码的.这是lsp协议通信库,用来帮助server(你的语言服务器) 和client(editor 类似vscode) 通信的. 它就是对lsp协议消息进行收发,解析的.

**Comment by kuafuwang** [comment]
你参考一下这个 [cquery](https://github.com/jacobdufault/cquery) ,看看别人的server怎么写.

**Comment by kuafuwang** [comment]
https://github.com/kuafuwang/LspCpp/blob/master/TcpServerExample.cpp
你看看这个例子中.
你需要做的就是
`endpoint.method2request[td_initialize::kMethodType] = [&](std::unique_ptr<LspMessage> msg)
		{
			auto req = reinterpret_cast<td_initialize::request*>(msg.get());
			td_initialize::response rsp;
			rsp.id = req->id;
			CodeLensOptions code_lens_options;
			code_lens_options.resolveProvider = true;
			rsp.result.capabilities.codeLensProvider = code_lens_options;
			server.remote_end_point_->sendResponse(rsp);
			return true;
		};`
		
在server中注册一下,你的语言服务器需要处理的 lsp请求,并返回响应.

**Comment by HaoWShi** [comment]
我就是想基于你封装的LSP协议，定义上层的实现，然后基于LSPCpp与server（已经实现了）利用LSP协议通信。

**Comment by HaoWShi** [comment]
我昨天就看了下你的这个例子，没看太明白（手动狗头）

**Comment by HaoWShi** [comment]
我在继续研究下

**Comment by kuafuwang** [comment]
lsp::ProtocolJsonHandler 这个类是负责将json 反序列成LspMessage的.这个我已经人力把涉及到的都写好了,除非你是要扩展才需要在添加新的Lsp message类型.

GenericEndpoint 这个类是负责将LspMessage 分发到相应的消息处理函数中的. 你如果像处理一个
[Initialize Request](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#initialize)
那你需要将这个request的处理函数注册一下,后面如果有client的Initialize Request 过来后,会自动调这个处理函数

endpoint.method2request["initialize"] = [&](std::unique_ptr msg)
{
auto req = reinterpret_cast<td_initialize::request*>(msg.get());
td_initialize::response rsp;
rsp.id = req->id;
CodeLensOptions code_lens_options;
code_lens_options.resolveProvider = true;
rsp.result.capabilities.codeLensProvider = code_lens_options;
server.remote_end_point_->sendResponse(rsp);
return true;
};
你需要在处理函数中按照lsp协议返回 响应.

**Comment by kuafuwang** [comment]
你等我重构一下这些接口.我感觉现在的接口感觉比较分散,不好用.

**Comment by kuafuwang** [comment]
好了.
我提供 了 registerRequestHandler ,registerNotifyHandler,waitResponse,sendNotification 这些接口.
registerRequestHandler  用来注册处理request消息的回调函数
registerNotifyHandler  用来注册处理notify消息的回调函数
要发生request消息并等待response响应,用waitResonse,
要发notify消息用sendNotification

**Comment by HaoWShi** [comment]
我在看看

**Comment by kuafuwang** [comment]
如果是实现client的话,
先初始化是必不可少的,
先发 [initialize request](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#initialize)

如果是添加或者移除指定的workspace目录发送[workspace_didChangeWorkspaceFolders notification ](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#workspace_didChangeWorkspaceFolders)

打开文件要告诉server 发[textDocument_didOpen notification ](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_didOpen)

那些修改了文件,关闭文件也有相应的notification 

想得到代码补全给server发[textDocument_completion request](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_completion)

**Comment by kuafuwang** [comment]
> ```c++
> #include "Endpoint.h"
> ```

还有别的报错吗? 在我机器没有,不知道怎么回事.

**Comment by kuafuwang** [comment]
大概就这样.你自己慢慢摸索吧.

**Comment by HaoWShi** [comment]
暂时没发现别的错误了。嗯，我自己在研究下哈。多谢了

**Comment by HaoWShi** [comment]
> 如果是实现client的话,
> 先初始化是必不可少的,
> 先发 [initialize request](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#initialize)
> 
> 如果是添加或者移除指定的workspace目录发送[workspace_didChangeWorkspaceFolders notification ](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#workspace_didChangeWorkspaceFolders)
> 
> 打开文件要告诉server 发[textDocument_didOpen notification ](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_didOpen)
> 
> 那些修改了文件,关闭文件也有相应的notification
> 
> 想得到代码补全给server发[textDocument_completion request](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_completion)

多谢！

**Comment by HaoWShi** [comment]
你好，我如果在Windows环境下要使用标准输入和输出流的话，该如何实现呀，我看你的代码里给了Tcp和WebSocket方式的

**Comment by HaoWShi** [comment]
你好，那边能不能给个标准输入和输出流的例子

**Comment by kuafuwang** [comment]
> 你好，那边能不能给个标准输入和输出流的例子
巧了,昨天上传了,在example目录里面有.另外给我这个项目点个星.

**Comment by kuafuwang** [comment]
> 你好，那边能不能给个标准输入和输出流的例子

巧了,昨天上传了,在example目录里面有.另外给我这个项目点个星.

**Comment by HaoWShi** [comment]
嘿嘿，点了

**Comment by HaoWShi** [comment]
![image](https://user-images.githubusercontent.com/20752268/115197428-8efffb00-a123-11eb-9af1-046fb39fc99b.png)
你好，我使用你的标准输入输出的例子，拉起了一个lua语言的lsp服务器，上面截图是输出的结果，textDocument/definition得到的是超时。但是lsp服务器是支持这个接口的https://github.com/sumneko/lua-language-server/blob/master/script/provider/provider.lua 323行。麻烦指导下是什么原因导致的

**Comment by kuafuwang** [comment]
> ![image](https://user-images.githubusercontent.com/20752268/115197428-8efffb00-a123-11eb-9af1-046fb39fc99b.png)
> 你好，我使用你的标准输入输出的例子，拉起了一个lua语言的lsp服务器，上面截图是输出的结果，textDocument/definition得到的是超时。但是lsp服务器是支持这个接口的https://github.com/sumneko/lua-language-server/blob/master/script/provider/provider.lua 323行。麻烦指导下是什么原因导致的

我那些例子是随便写的.
你初始化的时候要把工程目录发过去啊.
你没有指定工程目录,是不行的吧.
另外你获取文档的时候要先open 相应的文件,得到一个文件的url
你要获取相应的定义,你要告诉定义文档的 url, offset这些位置.
另外忘记说了.
`class DummyLog :public lsp::Log
{
public:

	void log(Level level, std::wstring&& msg)
	{
		
	};
	void log(Level level, const std::wstring& msg)
	{
		
	};
	void log(Level level, std::string&& msg)
	{
		
	};
	void log(Level level, const std::string& msg)
	{
		
	};
};
`
这里面的输出都去掉比较好,因为它会输出到server那边.

**Comment by kuafuwang** [comment]
你要自己看 [lsp 的规范](https://microsoft.github.io/language-server-protocol/specifications/specification-current/) 
发生相应的request之前,看看需要发送什么信息.或者看我代码中Params需要什么,需要什么就填什么,然后在发送request

**Comment by HaoWShi** [comment]
好的，我在研究下（手动哭脸）

**Comment by HaoWShi** [comment]
不过既然最初是的intialize能得到返回值，是不是就是说明当前的服务器和客户端是可以通过标准输出输入流进行通信的

**Comment by kuafuwang** [comment]
> 不过既然最初是的intialize能得到返回值，是不是就是说明当前的服务器和客户端是可以通过标准输出输入流进行通信的

这个不是很明显的吗?如果没有返回,是不是应该timeout啊?

**Comment by kuafuwang** [comment]
用 标准输出输入流进行通信 的时候,你要是想在命令行下打印log,  用 std::cerr 代替std::cout比较好.

**Comment by kuafuwang** [comment]
我看了看那个lua的server的实现,她应该在你没有传file的uri的时候,找不到file的时候,应该返回error信息,而不是直接返回了null,你可以给她提供issue,说让她的server提供详细一些错误的信息.

**Comment by HaoWShi** [comment]
> 用 标准输出输入流进行通信 的时候,你要是想在命令行下打印log, 用 std::cerr 代替std::cout比较好.

嗯嗯，多谢指导

**Comment by HaoWShi** [comment]
> 我看了看那个lua的server的实现,她应该在你没有传file的uri的时候,找不到file的时候,应该返回error信息,而不是直接返回了null,你可以给她提供issue,说让她的server提供详细一些错误的信息.

嗯嗯
